- .github/CODEOWNERS
- .github/settings.yml
- README.md
- tests/go.mod
depends on https://github.com/terraform-ibm-modules/repo-settings/pull/36
```
/run pipeline
```
> chore: Init

- README.md
- configure_project/main.tf
- configure_project/outputs.tf
- configure_project/providers.tf
- configure_project/variables.tf
- configure_project/versions.tf
- configure_user/main.tf
- configure_user/providers.tf
- configure_user/variables.tf
- cra-config.yaml
- examples/complete/main.tf
- examples/complete/variables.tf
- main.tf
- providers.tf
- tests/pr_test.go
- variables.tf
- version.tf
Use different apikeys for provisioning and configuration #24 
```
/run pipeline
```
> use different apikeys for provisioning and configuration

- main.tf
check if the watsonx admin apikey is empty, currently we only check if it is null. 
```
/run pipeline
```
> check if the watsonx admin apikey is empty

- .github/settings.yml
> add topic to enable issue sync

- README.md
- configure_project/outputs.tf
- ibm_catalog.json
- outputs.tf
> added project_location output

- .github/settings.yml
- configure_project/main.tf
- configure_project/outputs.tf
Outputs regex project ID
```
/run pipeline
```
> feat: project id regex

- README.md
- configure_project/main.tf
- configure_project/outputs.tf
- configure_project/variables.tf
- examples/basic/main.tf
- examples/basic/outputs.tf
- examples/complete/main.tf
- examples/complete/outputs.tf
- ibm_catalog.json
- main.tf
- outputs.tf
- variables.tf
> updated variable names related to watsonx project

- reference-architectures/watsonx-saas-da.md
Missing attributes in the ref architecture. 
```
/run pipeline
```
> Update missing attribute values

- reference-architectures/watsonx-saas-da.md
Added missing compliance attribute 
```
/run pipeline
```
> add compliance attribute

- README.md
- examples/basic/main.tf
- examples/basic/outputs.tf
- examples/complete/main.tf
- examples/complete/outputs.tf
- ibm_catalog.json
- main.tf
- outputs.tf
- tests/pr_test.go
- variables.tf
Rename references to discovery, assistant, and governance. fixes #52 
```
/run pipeline
```
> chore: rename references to discovery, assistant, and governance

- estimated-usage.yml
Update Infracost usage values for watsonx Machine Learning and watsonx Disovery resources. This will result in a more accurate cost estimate for this DA.
```
/run pipeline
```
> Update usage values

- README.md
- ibm_catalog.json
> Update files: Content review

- cra-config.yaml
We were using deprecated SCC profile. Updated to latest version.
```
/run pipeline
```
> update scc profile version

- README.md
- ibm_catalog.json
> fix: fixed iam permissions needed to create a watson project

- reference-architectures/watsonx-saas-da.md
> Better explain storage delegation option

- reference-architectures/watsonx-saas-da.md
- The reference architecture is not displaying in the Cloud docs in production.
It is in staging (https://test.cloud.ibm.com/docs/watsonx-ai-saas-automation?topic=watsonx-ai-saas-automation-watsonx-ai-reference-architecture) but not in production
- Version doesn't match DA version in the registry
```
/run pipeline
```
- Include information that users need to know about the PR in …
> Make ref arch available in public

- storage_delegation/main.tf
> fix: Storage delegation does not work when KMS is private

- outputs.tf
> fix: Error when requesting no project to be created

- README.md
- ibm_catalog.json
- reference-architectures/watsonx-saas-da.md
> Rename the DA

- README.md
- ibm_catalog.json
- reference-architectures/watsonx-saas-da.md
> Update catalog tile

- .catalog-onboard-pipeline.yaml
- README.md
- configure_project/main.tf
- configure_project/versions.tf
- main.tf
- renovate.json
> fix: SaaS DA is intermittently failing on deploy

- README.md
- main.tf
- outputs.tf
- variables.tf
> feat: Allow to use references to existing instances

- README.md
- configure_project/main.tf
- configure_project/outputs.tf
- main.tf
- outputs.tf
> fix:decode account from crn instead of IAM token

- examples/basic/main.tf
- examples/basic/variables.tf
- examples/complete/main.tf
This is a small alteration to the examples. The basic example can use Toyko or London. Both the basic and complete examples were not using the `location` as might reasonably be expected.
Note: Watson.governance is only supported in eu-de and us-south; so the complete example needs to be restricted to those two regions.
These changes were identified during a feasibility review for https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/118
```
/run pipeline
```
- Use a conventional commit message to set …
> fix: use location in examples

- main.tf
- storage_delegation/main.tf
- storage_delegation/variables.tf
- tests/pr_test.go
add fix to storage delegation to support different regions: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/148
I also made `cos_kms_crn` a required variable (remove default value) and updated the regex to only allow the supported regions.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The …
> fix: add fix to storage delegation to support different regions

- .github/CODEOWNERS
- .github/settings.yml
Transfer to core team
```
/run pipeline
```
> Transfer to core team

- README.md
- configure_project/main.tf
- configure_project/variables.tf
- ibm_catalog.json
- main.tf
- variables.tf
Variable has been added to allow the user to mark the project as sensitive.
Git issue: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/167
```
/run pipeline
```
> feat: allow user to mark project as sensitive

- .catalog-onboard-pipeline.yaml
- README.md
- catalogValidationValues.json.template
- cra-config.yaml
- examples/basic/main.tf
- examples/complete/main.tf
- main.tf
- variables.tf
Without the boolean, you get the error:
```
│ Error: Invalid count argument
│ 
│   on ../../main.tf line 311, in module "storage_delegation":
│  311:   count                = var.cos_kms_crn == null || var.cos_kms_crn == "" ? 0 : 1
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.
╵}
```
So I added a boolean and updated the count to use it instead.
I also made the required changes to run the pipeline in the GoldenEye dev account (https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/180)
If the CI pipeline doesn't run when you create the PR, the PR …
> fix: added new variable 'enable_cos_kms_encryption' to toggle KMS encryption

- .secrets.baseline
- configure_project/main.tf
- configure_user/scripts/add_user.sh
- configure_user/scripts/enforce_account_restriction.sh
- ibm_catalog.json
- tests/pr_test.go
Intermittently tests hitting this:
`Error: unexpected response code '400': Project name 'watsonx-poc-demo' already used.`
Added a unique prefix to all tests to avoid this.
I also updated the region list so we run tests against all of the support regions.
Fixed the eu-gb api (was incorrectly set to `eu-uk` instead of `eu-gb` in several places
```
/run pipeline
```
- Include …
> fix: Fixed the eu-gb api endpoint url + add prefix to test to avoid test clashes + added missing variables to ibm_catalog.josn

- configure_project/main.tf
- ibm_catalog.json
- variables.tf
Fixed incorrect plan names for watsonx orchestrate.
fixes https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/321
Plan names changed to reflect correct names used in watsonx Orchestrate.
```
/run pipeline
```
- …
> fix: corrected plan names for orchestrate
